### ISSUE TITLE
Every file change in npm run dev will create a new chrome tab

### ISSUE THREAD

**Issue by maximilianvoss** [adobe/adobeio-cna-starter-project#20]
When running npm run dev and do some code changes for example in an action an additional chrome tab will be automatically opened pointing to http://localhost:9800.
This can be very annoying when multiple changes are done and saved.

Way better would be, do nothing and let the developer refresh the page.

**Comment by moritzraho** [comment]
Good point this is indeed annoying.. making a PR to show the URL in the console instead of opening it

**Comment by moritzraho** [comment]
@maximilianvoss should be fine now, you can pull the latest changes or if you have problems merging, just remove the last line of `scripts/parcel.proxy.js`
Thank you for the feedback !

**Comment by maximilianvoss** [comment]
Great! Thanks a lot! :)
