### ISSUE TITLE
'NODE_ENV' not recognized on Windows

### ISSUE THREAD

**Issue by PulkitXChadha** [adobe/adobeio-cna-starter-project#5]
When running the command
'npm run dev' I get the following error
'NODE_ENV' is not recognized as an internal or external command

### Expected Behaviour
Start the local development server

### Actual Behaviour
get the following error
'NODE_ENV' is not recognized as an internal or external command

#### Steps to Reproduce
Running  'npm run dev' on Windows command line

**Comment by moritzraho** [comment]
@PulkitXChadha thanks for reporting the issue!
If you have git installed you can fix this for now by running: `npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"` (or `npm config set script-shell "C:\\Program Files (x86)\\git\\bin\\bash.exe"` if you have a 32bits install of git) - source https://stackoverflow.com/a/46006249

**Comment by moritzraho** [comment]
A fix has been merged now, no need to run the above command anymore. closing the issue
